spring.application.name=similar-products

server.port=5000
spring.threads.virtual.enabled=true

product-api.base-url=http://localhost:3001
product-api.connect-timeout=1s
product-api.read-timeout=2s
product-api.cache.ttl=30s
product-api.cache.failure-ttl=5s
product-api.cache.max-size=10000
